dist: bionic
language: c
addons:
  apt:
    sources:
      - sourceline: ppa:team-gcc-arm-embedded/ppa
    packages:
      - gcc-arm-embedded
script:
  - make release OUT=bcf-radio-voc-sensor-${TRAVIS_TAG} VERSION=${TRAVIS_TAG}
deploy:
  provider: releases
  cleanup: false
  file_glob: true
  file: out/release/*.bin
  overwrite: true
  on:
    tags: true
notifications:
  email: false
