article: https://www.bigclown.com/doc/projects/radio-voc-sensor/
#images:
#  - title:
#    url: https://www.bigclown.com/doc/projects/radio-voc-sensor/project-image.png
assembly:
  - name: HARDWARIO VOC Tag
  - name: HARDWARIO Temperature Tag
    optional: true
  - name: BigClown Humidity Tag
    optional: true
  - name: HARDWARIO Core Module
  - name: HARDWARIO Tag Module
    optional: true
  - name: HARDWARIO Battery Module
    optional: true
